#include "../types.h"
void SetUseOk(Sint16 unknown1, Sint16 unknown2, Sint16 unknown3);
void m2mainchk(void);
void m2subset(void);
void DLL_meminit(char ***pBufTbl, void **pFuncTbl);
void DLL_memfree(void);
Sint32 Get_vscroll(void);
Sint32 Get_scra_h_posiw(void);
Sint32 Get_scrb_h_posiw(void);
Sint32 game(void);
Sint32 ufochk(void);
void game_clear(void);
void game_over(void);
void game_init(void);
void syspatchg(void);
void sdfdout(void);
void sdfdin(void);
void disp(void);
Sint32 disp_main(void);
void gsc_up20(void);
void gsc_up(Sint32 lScore);
Sint16 pause_chk(void);
void map_init(void);
void bwrtset(Uint32 tblno4);
void stone_color_set(void);
void panel_box(void);
void colset(PALETTEENTRY *lpPeSrc);
void sinit0(void);
void sinit1(void);
void sinit2(void);
void sinit3(void);
void sinit4(void);
void sinit5(void);
void sinit6(void);
void sinit7(void);
void stage_init(void);
void soundset(Sint16 ReqNo);
void sub_sync(Sint16 ReqNo);
void key_set(Sint16 ReqNo);
void SWdataSet(ushort_union sw1, ushort_union sw2);
void hscal_1(void);
void hscal_2(void);
void hscal0_0(void);
void hscal1_0(void);
void hscal2_0(void);
void hscal0(Sint16 *a0, Sint16 *a1, Sint32 d0, Sint32 d1, Sint16 d3, Sint16 d4,
            Sint16 d7);
void hscal0_4(void);
void hscal1_4(void);
void hscal2_4(void);
void hscal4(Sint16 *a0, Sint16 *a1, Sint32 *a2, Sint16 d0, Sint16 d7);
void hscal0_5(void);
void hscal1_5(void);
void hscal2_5(void);
void hscal5(Sint16 *a0, char *a2, Sint16 d0, Sint16 d2, Sint16 d7);
void rlspd_get(Sint32 *d0, Sint32 *d1);
void hscrspd_get(Sint32 *lD0, Sint32 *lD1);
void hscrl0(void);
void hscrl1(void);
void hscrl2(void);
void hscrl3(void);
void hscrl4(void);
void hscrl5(void);
void hscrl6(void);
void hscrl7(void);
void hscal(void);
void colchg0(void);
void colchg1(void);
void colchg2(void);
void colchg3(void);
void colchg4(void);
void colchg5(void);
void colchg6(void);
void colchg7(void);
void color_change(void);
