#include "TYPES.H"

unsigned char flagwork[766];
short_union gameflag;
short_union gametimer;
short_union stageno;
int_union pltime;
uint_union debugwork;
short_union demoflag;
short_union debugflag;
int_union flowerposi[192];
unsigned char flowercnt[3];
short_union editno;
short_union editmode;
int_union systemtimer;
int_union scra_h_posiw;
int_union scra_v_posiw;
int_union scrb_h_posiw;
int_union scrb_v_posiw;
int_union scrc_h_posiw;
int_union scrc_v_posiw;
int_union scrz_h_posiw;
int_union scrz_v_posiw;
ushort_union scrflagaw;
ushort_union scrflagbw;
ushort_union scrflagcw;
ushort_union scrflagzw;
short_union col_y;
short_union col_x;
int linework[128];
unsigned short* pmapwk;
unsigned short blockwk[4][1024];
unsigned char flowwk[4096];
short hscrollwork[256];
sprite_statuses pbuffer[8];
short playposiwk[128];
int_union* lphscrollbuff;
sprite_status actwk[128];
short_union gmmode;
ushort_union swdata;
ushort_union swdata1;
ushort_union swdata2;
int_union vscroll;
int_union hscroll;
short_union hintposi;
short_union intcnt;
ushort_union pauseflag;
unsigned char cgchgcnt[6];
unsigned char cgchgtim[6];
unsigned int divdevwk[24];
int_union scra_h_posit;
int_union scra_v_posit;
int_union scrb_h_posit;
int_union scrb_v_posit;
int_union scrc_h_posit;
int_union scrc_v_posit;
int_union scrz_h_posit;
int_union scrz_v_posit;
ushort_union zone_flag;
short_union scroll_start;
ushort_union scr_die;
short_union scr_timer;
ushort_union scrflaga;
ushort_union scrflagb;
ushort_union scrflagc;
ushort_union scrflagz;
char dirstk[4];
short_union actset_rno;
aset_info* asetadr;
aset_info* asetadr2;
asetz_info* asetadrz;
asetz_info* asetadrz2;
short_union byecnt0;
short_union byecnt1;
unsigned char* scdadr;
ushort_union plposiwkadr;
unsigned char clchgcnt[7];
unsigned char clchgtim[7];
short_union waterdirec;
unsigned char switchflag[32];
PALETTEENTRY* lpcolorwk;
PALETTEENTRY* lpcolorwk2;
PALETTEENTRY* lpcolorwk3;
PALETTEENTRY* lpcolorwk4;
int* lpFadeFlag;
game_info* lpKeepWork;
unsigned char ms_wflg;
unsigned char edplayflag;
unsigned char bonus_f;
short ringbonus;
short timebonus;
short emyscorecnt;
unsigned char dai2rmvflag;
unsigned char specflag;
unsigned char plautoflag;
unsigned char sekichyuflag;
unsigned char mizuflag;
unsigned char waterstop;
unsigned char watercoliflag;
unsigned char ballmapno2;
unsigned char ballmapno;
unsigned char loopmapno2;
unsigned char loopmapno;
unsigned char bossstart;
unsigned char bossflag;
short scra_hline;
short swbufcnt;
short demo_cnt;
unsigned int demo_adr;
unsigned char scr_cnt;
short backto_cnt;
char time_item;
short asetposi;
unsigned char playwrtflag;
unsigned char playpatno;
short plretspdwk;
short pladdspdwk;
short plmaxspdwk;
unsigned char kusya_flag;
unsigned char playpatno1;
unsigned char limmoveflag;
unsigned char scrz_v_count;
unsigned char scrz_h_count;
unsigned char scrc_v_count;
unsigned char scrc_h_count;
unsigned char scrb_v_count;
unsigned char scrb_h_count;
unsigned char scra_v_count;
unsigned char scra_h_count;
unsigned char scrv_flag;
unsigned char scrh_flag;
short scra_vline;
short scra_vz;
short scra_hz;
short scra_v_keep;
short scra_h_keep;
short scrar_no;
short scralim_down;
short scralim_up;
short scralim_right;
short scralim_left;
short scralim_n_down;
short scralim_n_up;
short scralim_n_right;
short scralim_n_left;
unsigned short hintflag;
short bitdevcnt2;
short bitdevcnt;
unsigned short bitdevadr;
unsigned char waterflag2;
unsigned char waterflag;
unsigned char water_flag;
unsigned char waterspeed;
short watermoveposi;
short waterposi_m;
short waterposi;
int dmastack;
short cgwrttim;
short cgwrtcnt;
int ranum;
int cltbladr;
unsigned char linkdata;
unsigned char int_flg;
unsigned char colorcnt;
unsigned char startcolor;
short waittimer;
short sprpage;
int stacksave;
unsigned int sbufadr;
unsigned char mapwrt_cnt;
unsigned char chibi_flag;
unsigned char st6clrchg;
unsigned char shut_flag;
unsigned char boss_sound;
unsigned char init_flag;
unsigned char prio_flag;
unsigned char sysdirec;
unsigned char edit_user;
short blkno;
short mapcheck;
short editstack2;
short editstack;
short sys_ringtimer;
unsigned char sys_patno4;
unsigned char sys_pattim4;
unsigned char sys_patno3;
unsigned char sys_pattim3;
unsigned char sys_patno2;
unsigned char sys_pattim2;
unsigned char sys_patno;
unsigned char sys_pattim;
short time_stop;
short edittimer;
unsigned char tv_flag;
unsigned char prio_s;
unsigned char chibi_s;
unsigned char gf_flag;
unsigned char colrevflag;
unsigned char markerno;
unsigned int resetflg;
unsigned char mdstatus;
short enddemono;
short demono;
int extrascore;
unsigned char emie3end;
unsigned char enecgpnt;
unsigned char enecgflg;
unsigned char conbine_flag;
unsigned char special_flag;
unsigned char projector_flag;
unsigned char enkeino;
unsigned char plsubchg_flag;
unsigned char generate_flag;
unsigned char plring_f2_s;
unsigned char waterflag_s;
unsigned char water_flag_s;
short waterposi_m_s;
short scrz_v_posit_s;
short scrz_h_posit_s;
short scrc_v_posit_s;
short scrc_h_posit_s;
short scrb_v_posit_s;
short scrb_h_posit_s;
short scra_v_posit_s;
short scra_h_posit_s;
short scralim_down_s;
unsigned char time_flag;
int pltime_s;
short plring_s;
short plyposi_s;
short plxposi_s;
unsigned char plflag_s;
unsigned char plflag;
unsigned char plpower_a;
unsigned char plpower_s;
unsigned char plpower_m;
unsigned char plpower_b;
unsigned char start_flag;
unsigned char play_start;
int plscore;
short plring;
unsigned char plscore_f;
unsigned char pltime_f;
unsigned char plring_f;
unsigned char pl_suu_f;
unsigned char plring_f2;
unsigned char pltimeover_f;
short pl_air;
unsigned char main_play;
unsigned char pl_suu;
unsigned char play_status;
unsigned char flagworkcnt2;
unsigned char flagworkcnt;
unsigned char clrspflg_save;
unsigned char ta_flag;
