#include "types.h"
void patchg(sprite_status* patchgwk, Uint8** pat_dat);
void playsave0(sprite_status* savewk);
void marker(sprite_status* markerwk);
void marker_init(sprite_status* markerwk);
void marker_move0(sprite_status* markerwk);
void marker_move1(sprite_status* markerwk);
void marker_move2(sprite_status* markerwk);
void plairset(void);
void test_act(sprite_status* testwk);
void test_init(sprite_status* testwk);
void test_move(sprite_status* testwk);
void tensuu_set(sprite_status* tensuuwk);
void tensuu0(sprite_status* tensuuwk, Uint8 uf_data);
void bakuha(sprite_status* bakuhawk);
void baku_init(sprite_status* bakuhawk);
void baku_move(sprite_status* bakuhawk);
void baku_die(sprite_status* bakuhawk);
void flower(sprite_status* flowerwk);
void flow_init(sprite_status* flowerwk);
void flow_move0(sprite_status* flowerwk);
void flow_move1(sprite_status* flowerwk);
Uint8* flow_sub(sprite_status* flowerwk);
Sint16 flow_sub1(Uint8 fl_counter);
void flow_move2(sprite_status* flowerwk);
void flow_move3(sprite_status* flowerwk);
void mizukiri(sprite_status* mizukiwk);
void mizuki_init(sprite_status* mizukiwk);
void mizuki_move(sprite_status* mizukiwk);
void mizuki_move2(sprite_status* mizukiwk);
void futa(sprite_status* futawk);
void ride_on_chk_f(sprite_status* futawk, sprite_status* sonicwk);
void futa_init(sprite_status* futawk);
void futa_move(sprite_status* futawk);
void futa_move2(sprite_status* futawk);
void futa_move3(sprite_status* futawk);
void exit2_set(sprite_status* testwk);
char col_chk(sprite_status* thingwk, sprite_status* sonicwk);
void exit2(sprite_status* exitwk);
void exit2_init(sprite_status* exitwk);
void exit2_move(sprite_status* exitwk);
void exit2_erase(sprite_status* exitwk);
void baria(sprite_status* bariawk);
void bariainit(sprite_status* bariawk);
void bariamove(sprite_status* bariawk);
void mutekimove(sprite_status* bariawk);
void backtomove(sprite_status* bariawk);
void muteki_sub(sprite_status* bariawk);
void actionsub0(sprite_status* bariawk);
void ball(sprite_status* ballwk);
void ball_init(sprite_status* ballwk);
void ball_move(sprite_status* ballwk);
void ball_ball(void);
void ball_rd7(sprite_status* ballwk);
Uint8 ball_coli(sprite_status* ballwk);
