#include "types.h"
void bye_chk(void);
void play00(sprite_status* actionwk);
void muteki_set(void);
void test_mapwrt(void);
void play00init(void);
void mizuki_set(void);
Uint32 mapno_chk(Sint16 d2, Sint16 d3);
void kuru2(void);
void bura(void);
void sibi2(void);
void sibi(void);
void bfloor(void);
void scr_h(void);
void play00move(void);
void playpowercnt(void);
void playposiwkset(void);
void plwaterchk(void);
void playsave(void);
void backto_chk(void);
void play00walk(void);
void play00jump(void);
void ball00walk(void);
void ball00jump(void);
void kuru2move(void);
void buramove(void);
void chk11(void);
void levermove(void);
void lmovecol(void);
void plwalk_l(void);
void plwalk_r(void);
void balllmove(void);
void ballwalk_l(void);
void ballwalk_r(void);
void jumpmove(void);
void hedcolchk(void);
void limitchk(void);
void ballchk(void);
void ballset(void);
Uint8 jumpchk(void);
void jumpchk2(void);
void keispd(void);
void keispd2(void);
void fallchk(void);
void direcchg(void);
void jumpcolchk(void);
void jumpcolsub(void);
void jumpcolsub0(void);
void play00damage(void);
void play00damage_sub(void);
void play00die(void);
void play00die_sub(void);
void play00erase(void);
void loopchk(void);
void st7_x(void);
void patchgmain(void);
void patchgmain2(Uint8* pat_pointer);
void playrunchg(Uint8 pat_no);
void playrunchg2(Uint8 pat_no);
void playrunchg3(Uint8 pat_no);
void playetc_chg(void);
void little_runchg(void);
char little_patchg(char pat_index);
void playwrt(void);
Uint8 frip_spd(Sint32* cal_jump, Uint8* cal_direc);
